cpu_input_boost: fix building with GCC
../drivers/cpufreq/cpu_input_boost.c: In function ‘get_boost_freq’:
../drivers/cpufreq/cpu_input_boost.c:50:2: error: statement with no
effect [-Werror=unused-value]
  for (cpu; cpu < NR_CPUS; ++cpu) {
  ^~~
cc1: all warnings being treated as errors

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>